### PR TITLE
Fixes

### LINKED ISSUE #12: julia: command not found
I'm seeing this failure

> ```
> Julia 1 successfully installed to
> /etc/buildkite-agent/plugins/github-com-JuliaCI-julia-buildkite-plugin-v1/hooks/pre-command: line 144: julia: command not found
> ```
>
> https://buildkite.com/julialang/foldskernelabstractions-dot-jl/builds/32#1bf8859f-f2dd-4a31-90f2-e9712fe10c5c https://github.com/JuliaFolds/FoldsKernelAbstractions.jl/pull/11

from

https://github.com/JuliaCI/julia-buildkite-plugin/blob/2ec318d9e84fd5b6a402d926e7451e8b57b77d6c/hooks/pre-command#L143-L144

The same setting worked before (~ a month ago) https://buildkite.com/julialang/foldskernelabstractions-dot-jl/builds/28#a68e1685-3e7b-4aac-9896-cf5397276d47

### PR DESCRIPTION
**Pull request by maleadt**
Closes https://github.com/JuliaCI/julia-buildkite-plugin/issues/12

### CODE REVIEW

**Comment by maleadt** [comment]
Going to merge this a little quicker than I'd normally do, because this currently breaks CUDA.jl CI.

**Comment by maleadt** [comment]
Running here to test: https://buildkite.com/julialang/cuda-dot-jl/builds/1278

**Comment by maleadt** [comment]
Passes CI there.

**Comment by staticfloat** [comment]
Thanks Tim!

**Pull request merged**
